from __future__ import annotations

import pprint

from mon.exporters.base import BaseExporter
from mon.models.result import InspectResult


class PythonExporter(BaseExporter):
    """Writes the result as an importable Python module -- the default
    ``output_format``, letting callers ``from output.example_com import DATA``
    without needing a JSON/YAML parser at all."""

    extension = ".py"

    def export(self, result: InspectResult) -> str:
        data = result.to_dict()
        formatted = pprint.pformat(data, indent=2, width=100, sort_dicts=False)
        return (
            '"""Auto-generated by MON (Moson Web Intelligence Engine). Do not edit by hand."""\n\n'
            f"DATA = {formatted}\n"
        )
